/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a full install and is checked in here so TypeScript can resolve framework types from day one.
